### ISSUE TITLE
Organising Issue

### ISSUE THREAD

**Issue by Akshu-on-github** [Akshu-on-github/MLH-H4H#1]
### Preparation:
  - [x] Identify 5 categories that we'll be working on
  - [x] Find/Create datasets for each category
  - [x] Clean Datasets
  - [x] Note any other ideas

### Milestone 1: Main Tasks
  - [x] #2
  - [x] #3
  - [x] #6
  - [x] #4
  - [x] #5

### Hacking Milestone 2: Good to have
  - [x] Tips and tricks to reduce consumption
  - [x] Create a CI/CD pipeline for Streamlit deployment with GitHub Actions

### Submission
- [x] Create 2min demo and upload it to YouTube
- [x] Add a README.md to this repo
- [x] Create a project submission on [Devpost](https://hacks-for-hackers.devpost.com/)
- [x] Attach planning/design files, code repo, deployed link, etc.
